### PR TITLE
Added hook for OCP\Share::validatePassword event

### PR DESCRIPTION
**Pull request by mdusher**
Just added a listener for the OCP\Share::validatePassword event so that the password policy applies to shares as well.

### CODE REVIEW

**Comment by karakayasemi** [comment]
AFAIK, there is a plan for convert this app to only brute force protection app if enterprise password_policy app turns to a community application in the marketplace. Also, the password_policy app already has this feature. @DeepDiver1975 what are your thoughts on this topic?

**Comment by mdusher** [comment]
@karakayasemi from a user perspective, I'd say it would be a useful info line to have if the password policy code is going to remain in the app.

My use case is that we're looking at applying a password policy to our ownCloud instance and our security team has required brute force protection as part of that policy which was what prompted me to look at this app over password_policy.

**Comment by mdusher** [comment]
Just as an FYI, I stripped out the password policy feature in this branch:
https://github.com/AARNet/security/tree/bruteforceonly

**Comment by karakayasemi** [comment]
since we will deprecate this app, I am closing this PR. @mdusher thank you for your contribution. I will use your brute force only branch for new brute force app.

**Pull request closed without merging**
