### PR TITLE
block ip+uid combination instead of only ip

### PR DESCRIPTION
**Pull request by karakayasemi**
implementation of #27

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Nice! THX a lot!

**Comment by DeepDiver1975** [comment]
no database schema change required? @karakayasemi

**Comment by karakayasemi** [comment]
No change required for this PR. We are already storing uid in database.

**Comment by individual-it** [comment]
@karakayasemi still does not work for me. In Hooks.php you still calling the old delete function
```
    public function postLoginCallback() {
        $this->throttle->clearSuspiciousAttemptsForIp($this->request->getRemoteAddress());
    }
```
some end-to-end tests would be good here to test all this cases

**Comment by karakayasemi** [comment]
@individual-it Thanks for your help. I believe, I solved the problem this time. I have no experience in end-to-end testing, but I would like to add. Where should these tests place in the folder structure?

**Comment by individual-it** [comment]
@karakayasemi we put the usually into `tests/ui`
Currently we are using Behat & Mink to run UI tests on travis and saucelabs.com
The documentation about core UI tests can be found here https://doc.owncloud.org/server/10.0/developer_manual/core/ui-testing.html
and an example how the setup works for an app in the texteditor app https://github.com/owncloud/files_texteditor
I'm happy to help if you have any questions

**Comment by karakayasemi** [comment]
@DeepDiver1975 I guess we can merge this. I will create a new issue for end-to-end tests.

**Pull request merged**
