### PR TITLE
Add oracle test

### PR DESCRIPTION
**Pull request by karakayasemi**
Add oracle support on travis. #5

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
This needs some more to be added - e.g. https://github.com/owncloud/oauth2/pull/42

**Comment by DeepDiver1975** [comment]
@karakayasemi will you continue with this? THX

**Comment by karakayasemi** [comment]
Yes, I will when I make time for it. Thanks.

**Comment by karakayasemi** [comment]
Finally, all tests succeeded. There was a problem in before_install_oracle_module.sh. IMHO, the other repos which have tests for Oracle should apply the change to script for php7 and 7.1 with oracle env.
https://github.com/owncloud/security/blob/2a9c9cf08c0c4359362d57da94e05b23c19fa2cf/tests/.travis/before_install_oracle_module.sh#L12

**Pull request merged**
